// PDF and Markdown export utilities for StackTrace playbook generation

import { jsPDF } from "jspdf";
import { marked } from "marked";
import type { AnalysisResult } from "./types";

/**
 * Generate playbook markdown content from analysis result
 */
function generatePlaybookMarkdown(repoName: string, analysisData: AnalysisResult): string {
  const { architecture, gotchas, contributorGuide, deploymentRunbook, codingStandards, playbook } = analysisData;
  
  let markdown = `# ${repoName} Team Playbook\n`;
  markdown += `# Generated by StackTrace · IBM Bob Hackathon 2026\n\n`;
  markdown += `**Analysis Date:** ${new Date().toLocaleDateString()}\n`;
  markdown += `**Overall Confidence:** ${(playbook.overallConfidence * 100).toFixed(0)}%\n`;
  markdown += `**Ready for Onboarding:** ${playbook.readyForOnboarding ? "✅ Yes" : "⚠️ Needs Review"}\n\n`;
  
  markdown += `---\n\n`;
  
  // Architecture Section
  markdown += `## 🏗️ Architecture Overview\n\n`;
  markdown += `**Framework:** ${architecture.framework}\n\n`;
  markdown += `**Patterns Detected:**\n`;
  architecture.patterns.forEach(pattern => {
    markdown += `- ${pattern}\n`;
  });
  markdown += `\n**Key Dependencies:**\n`;
  architecture.dependencies.forEach(dep => {
    markdown += `- ${dep}\n`;
  });
  markdown += `\n**Confidence:** ${(architecture.confidence * 100).toFixed(0)}%\n\n`;
  
  // Gotchas Section
  markdown += `## ⚠️ Critical Gotchas\n\n`;
  gotchas.forEach((gotcha, index) => {
    const severityEmoji = gotcha.severity === "high" ? "🔴" : gotcha.severity === "medium" ? "🟡" : "🟢";
    markdown += `### ${index + 1}. ${severityEmoji} ${gotcha.title}\n\n`;
    markdown += `${gotcha.description}\n\n`;
    markdown += `- **File:** \`${gotcha.filePath}\`\n`;
    markdown += `- **Severity:** ${gotcha.severity.toUpperCase()}\n`;
    markdown += `- **Confidence:** ${(gotcha.confidence * 100).toFixed(0)}%\n\n`;
  });
  
  // Contributor Guide Section
  markdown += `## 👥 Contributor Guide\n\n`;
  markdown += `### Setup Steps\n\n`;
  contributorGuide.setupSteps.forEach((step, index) => {
    markdown += `${index + 1}. ${step}\n`;
  });
  markdown += `\n### Testing Strategy\n\n`;
  markdown += `${contributorGuide.testingStrategy}\n\n`;
  markdown += `### PR Process\n\n`;
  markdown += `${contributorGuide.prProcess}\n\n`;
  markdown += `**Confidence:** ${(contributorGuide.confidence * 100).toFixed(0)}%\n\n`;
  
  // Deployment Runbook Section
  markdown += `## 🚀 Deployment Runbook\n\n`;
  markdown += `**Build Command:** \`${deploymentRunbook.buildCommand}\`\n\n`;
  markdown += `**Required Environment Variables:**\n`;
  deploymentRunbook.envVars.forEach(envVar => {
    markdown += `- \`${envVar}\`\n`;
  });
  markdown += `\n**Deployment Steps:**\n`;
  deploymentRunbook.deploymentSteps.forEach((step, index) => {
    markdown += `${index + 1}. ${step}\n`;
  });
  markdown += `\n**Confidence:** ${(deploymentRunbook.confidence * 100).toFixed(0)}%\n\n`;
  
  // Coding Standards Section
  markdown += `## 📝 Coding Standards\n\n`;
  if (codingStandards.linter) {
    markdown += `**Linter:** ${codingStandards.linter}\n`;
  }
  if (codingStandards.formatter) {
    markdown += `**Formatter:** ${codingStandards.formatter}\n`;
  }
  markdown += `\n**Conventions:**\n`;
  codingStandards.conventions.forEach(convention => {
    markdown += `- ${convention}\n`;
  });
  markdown += `\n**Confidence:** ${(codingStandards.confidence * 100).toFixed(0)}%\n\n`;
  
  // Summary Section
  markdown += `---\n\n`;
  markdown += `## 📊 Playbook Summary\n\n`;
  markdown += `### Strengths\n\n`;
  playbook.strengths.forEach(strength => {
    markdown += `- ✅ ${strength}\n`;
  });
  markdown += `\n### Missing Information\n\n`;
  if (playbook.missingInfo.length > 0) {
    playbook.missingInfo.forEach(info => {
      markdown += `- ⚠️ ${info}\n`;
    });
  } else {
    markdown += `- None detected\n`;
  }
  
  markdown += `\n---\n\n`;
  markdown += `*Generated by StackTrace using IBM Bob*\n`;
  
  return markdown;
}

/**
 * Export playbook as Markdown file
 */
export function exportMarkdown(repoName: string, analysisData: AnalysisResult): void {
  const markdown = generatePlaybookMarkdown(repoName, analysisData);
  
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${repoName}-playbook.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export playbook as PDF file
 */
export function exportPDF(repoName: string, analysisData: AnalysisResult): void {
  const markdown = generatePlaybookMarkdown(repoName, analysisData);
  const html = marked(markdown) as string;
  
  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });
  
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - 2 * margin;
  
  // Header on first page
  pdf.setFillColor(26, 173, 126); // Teal accent color
  pdf.rect(0, 0, pageWidth, 12, "F");
  
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(10);
  pdf.text("StackTrace", margin, 8);
  pdf.text(repoName, pageWidth - margin, 8, { align: "right" });
  
  // Parse HTML and add content
  const tempDiv = document.createElement("div");
  tempDiv.innerHTML = html;
  
  let yPosition = 20;
  const lineHeight = 7;
  
  // Process each element
  const processNode = (node: Node) => {
    if (node.nodeType === Node.TEXT_NODE) {
      const text = node.textContent?.trim();
      if (text) {
        pdf.setTextColor(0, 0, 0);
        pdf.setFontSize(10);
        const lines = pdf.splitTextToSize(text, contentWidth);
        
        lines.forEach((line: string) => {
          if (yPosition > pageHeight - 30) {
            addFooter();
            pdf.addPage();
            yPosition = margin;
          }
          pdf.text(line, margin, yPosition);
          yPosition += lineHeight;
        });
      }
    } else if (node.nodeType === Node.ELEMENT_NODE) {
      const element = node as HTMLElement;
      
      if (element.tagName === "H1") {
        if (yPosition > margin + 10) {
          yPosition += 5;
        }
        pdf.setFontSize(18);
        pdf.setFont("helvetica", "bold");
        pdf.setTextColor(26, 173, 126);
        const text = element.textContent || "";
        pdf.text(text, margin, yPosition);
        yPosition += 10;
        pdf.setFont("helvetica", "normal");
      } else if (element.tagName === "H2") {
        if (yPosition > pageHeight - 40) {
          addFooter();
          pdf.addPage();
          yPosition = margin;
        }
        yPosition += 5;
        pdf.setFontSize(14);
        pdf.setFont("helvetica", "bold");
        pdf.setTextColor(0, 0, 0);
        const text = element.textContent || "";
        pdf.text(text, margin, yPosition);
        yPosition += 8;
        pdf.setFont("helvetica", "normal");
      } else if (element.tagName === "H3") {
        yPosition += 3;
        pdf.setFontSize(12);
        pdf.setFont("helvetica", "bold");
        const text = element.textContent || "";
        pdf.text(text, margin, yPosition);
        yPosition += 7;
        pdf.setFont("helvetica", "normal");
      } else if (element.tagName === "P") {
        element.childNodes.forEach(processNode);
        yPosition += 3;
      } else if (element.tagName === "UL" || element.tagName === "OL") {
        element.childNodes.forEach((child, index) => {
          if (child.nodeType === Node.ELEMENT_NODE && (child as HTMLElement).tagName === "LI") {
            if (yPosition > pageHeight - 30) {
              addFooter();
              pdf.addPage();
              yPosition = margin;
            }
            const bullet = element.tagName === "UL" ? "•" : `${index + 1}.`;
            const text = child.textContent?.trim() || "";
            const lines = pdf.splitTextToSize(text, contentWidth - 10);
            
            pdf.text(bullet, margin + 2, yPosition);
            lines.forEach((line: string, lineIndex: number) => {
              pdf.text(line, margin + 10, yPosition + lineIndex * lineHeight);
            });
            yPosition += lines.length * lineHeight;
          }
        });
        yPosition += 2;
      } else if (element.tagName === "HR") {
        yPosition += 3;
        pdf.setDrawColor(200, 200, 200);
        pdf.line(margin, yPosition, pageWidth - margin, yPosition);
        yPosition += 5;
      } else if (element.tagName === "CODE") {
        pdf.setFont("courier");
        pdf.setTextColor(100, 100, 100);
        const text = element.textContent || "";
        pdf.text(text, margin, yPosition);
        yPosition += lineHeight;
        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(0, 0, 0);
      } else if (element.tagName === "STRONG" || element.tagName === "B") {
        pdf.setFont("helvetica", "bold");
        element.childNodes.forEach(processNode);
        pdf.setFont("helvetica", "normal");
      } else {
        element.childNodes.forEach(processNode);
      }
    }
  };
  
  const addFooter = () => {
    const pageNumber = pdf.internal.pages.length - 1;
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    const footerText = `Generated by StackTrace using IBM Bob — ${new Date().toLocaleDateString()}`;
    pdf.text(footerText, margin, pageHeight - 10);
    pdf.text(`Page ${pageNumber}`, pageWidth - margin, pageHeight - 10, { align: "right" });
  };
  
  tempDiv.childNodes.forEach(processNode);
  addFooter();
  
  pdf.save(`${repoName}-playbook.pdf`);
}

// Made with Bob
